apiVersion: apps/v1
kind: Deployment
metadata:
  name: okqwe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okqwe
  template:
    metadata:
      labels:
        app: okqwe
    spec:
      containers:
      - image: okteto.dev/okqwe:latest
        name: okqwe
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "5a3d2e79-f112-4162-a01a-287c99b7397b"
        - name: Vless_Path
          value: "/vless"
        - name: Vmess_UUID
          value: "5a3d2e79-f112-4162-a01a-287c99b7397b"
        - name: Vmess_Path
          value: "/vmess"
        - name: Share_Path
          value: "/hugy"
